# Generated by Django 3.2.4 on 2021-09-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_commenting_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.ImageField(default='venue_event_photo/venues.jpg', upload_to='venue_event_photo/'),
        ),
    ]
