# Generated by Django 3.2.4 on 2021-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='event_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
