# Generated by Django 3.2.4 on 2021-09-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='event_photos/events.jpg', upload_to='event_photos/'),
        ),
    ]
