# Generated by Django 3.2.4 on 2021-09-11 14:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type_of_user', models.CharField(blank=True, choices=[('user', 'User'), ('artist', 'Artist'), ('venue_rep', 'Venue Representative'), ('event_rep', 'Event Representative')], max_length=30, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('intersex', 'Intersex')], max_length=10, null=True)),
                ('type_of_artists', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organisation_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('venue_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
