# Generated by Django 3.2.4 on 2021-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='event_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
