# Generated by Django 3.2.4 on 2021-09-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
